language: objective-c
env:
  - RVM_RUBY_VERSION=1.9.3 NOEXEC_DISABLE=1 RUBY_VERSION_SPECIFIC='sudo ln -s /usr/bin/llvm-gcc-4.2 /usr/bin/gcc-4.2 && curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem' SSL_CERT_FILE=/usr/local/share/cacert.pem
before_install:
  - source ~/.rvm/scripts/rvm && rvm use $RVM_RUBY_VERSION
  - sudo chown -R $USER /usr/local
install: eval $RUBY_VERSION_SPECIFIC && bundle install
script: bundle exec rake spec